FROM debian:bookworm-slim

RUN apt-get update -qq && \
    apt-get install -y -qq --no-install-recommends \
        gnucobol4 libcurl4-openssl-dev ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app
COPY app.cob ./

RUN cobc -x -free -o app app.cob -Q "-Wl,--no-as-needed" -lcurl

RUN mkdir -p /tmp/sessions

ENV PORT=16439

EXPOSE 16439

COPY start.sh .
RUN sed -i 's/\r$//' start.sh && chmod +x start.sh

CMD ["./start.sh"]
